# Generated by Django 6.0.1 on 2026-03-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=55)),
                ('tags', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
